version: 2

project_name: tessera

builds:
  - id: coordinator
    main: ./cmd/coordinator
    binary: coordinator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/emmayusufu/tessera/internal/version.Version={{.Version}}

  - id: agent
    main: ./cmd/agent
    binary: agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/emmayusufu/tessera/internal/version.Version={{.Version}}

  - id: tessera
    main: ./cmd/tessera
    binary: tessera
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/emmayusufu/tessera/internal/version.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github

release:
  github:
    owner: emmayusufu
    name: tessera
  draft: true

brews:
  - name: tessera
    repository:
      owner: emmayusufu
      name: homebrew-tessera
    commit_msg_template: "tessera {{ .Version }}"
    install: |
      bin.install "coordinator"
      bin.install "agent"
      bin.install "tessera"
